### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by han265** [luolundashu/crawler_for_ai_conference#1]
There seems to be a spelling mistake in the headline: it's 'crawler‘ rather than 'crawer'. 
![IMG_1502](https://github.com/luolundashu/crawer_for_ai_conference/assets/115164294/06a22b4f-cd13-4858-8e4a-c7fbc4ee7a1a)

**Comment by luolundashu** [comment]
This issue has been resolved. Thank you for your attention.
